services:
    Grizzlylab\Bundle\MailerBundle\Mailer\Mailer:
        arguments: ["@mailer", "@twig",  {'address': "%mailer_sender_address%", 'name': "%mailer_sender_name%"}]

    grizzlylab_mailer:
        alias: Grizzlylab\Bundle\MailerBundle\Mailer\Mailer
        public: true
