parameters:
    grizzlylab_mailer.class: Grizzlylab\Bundle\MailerBundle\Service\MailerService

services:
    grizzlylab_mailer:
        class: "%grizzlylab_mailer.class%"
        arguments: ["@mailer", "@templating",  {'address': "%mailer_sender_address%", 'name': "%mailer_sender_name%"}]
